from random import randint
import datetime
ransom = randint(0,600)
ransom1 = randint(0,47)
ransom2 = randint(0,7)
ransom3 = randint(0,25)
now = datetime.datetime.now()
datem = now.year
year = randint(1940,2012)
month = randint(1,12)
day = randint(1,31)
age = int(datem) - year
################################## previne que os dados saiam da realidade
if month == '2' and day >= '29':
	day = 28
NOMES = [
    "Aaron",
    "Abel",
    "Abelardo",
    "Abelino",
    "Abiel",
    "Abiezer",
    "Abílio",
    "Abner",
    "Abraão",
    "Acácio",
    "Adailton",
    "Adair",
    "Adalberto",
    "Adalgiso",
    "Adalício",
    "Adalmir",
    "Adalto",
    "Adam",
    "Adamastor",
    "Adamor",
    "Adão",
    "Adeci",
    "Adeildo",
    "Adelair",
    "Adélcio",
    "Adelino",
    "Adélio",
    "Adelson",
    "Ademar",
    "Ademilson",
    "Ademir",
    "Aderbal",
    "Adérito",
    "Adilson",
    "Admilson",
    "Adolfo",
    "Adonai",
    "Adonis",
    "Adónis",
    "Adrian",
    "Adriano",
    "Adriel",
    "Aécio",
    "Afonso",
    "Afrânio",
    "Agenor",
    "Ageo",
    "Agipino",
    "Agnaldo",
    "Agnelo",
    "Agostinho",
    "Aguinaldo",
    "Ailton",
    "Aires",
    "Airton",
    "Aitor",
    "Alair",
    "Alaôr",
    "Alarico",
    "Albano",
    "Albertino",
    "Albino",
    "Alcides",
    "Alcindo",
    "Aldair",
    "Aldemir",
    "Aldenor",
    "Aldo",
    "Alejandro",
    "Alessandro",
    "Alex",
    "Alexandrino",
    "Alexandro",
    "Aléxio",
    "Alfredo",
    "Alípio",
    "Alírio",
    "Alison",
    "Allan",
    "Almerindo",
    "Almir",
    "Aloísio",
    "Alonzo",
    "Altino",
    "Aluísio",
    "Alvantino",
    "Alvino",
    "Amadeo",
    "Amândio",
    "Amarildo",
    "Amauri",
    "Amaury",
    "Ambrósio",
    "Américo",
    "Amílcar",
    "Amilton",
    "Amir",
    "Ananias",
    "Andersen",
    "Anderson",
    "Ândreo",
    "Andrés",
    "Anésio",
    "Angélico",
    "Ângelo",
    "Aníbal",
    "Anísio",
    "Anselmo",
    "Antenor",
    "Antero",
    "Anthony",
    "Apollo",
    "Apolo",
    "Aprígio",
    "Aquiles",
    "Arcanjo",
    "Aristeu",
    "Aristides",
    "Armando",
    "Armindo",
    "Arnaldo",
    "Arthur",
    "Arturo",
    "Ary",
    "Asher",
    "Assis",
    "Ataíde",
    "Athos",
    "Átila",
    "Atlas",
    "Aureliano",
    "Aurelino",
    "Aurélio",
    "Aurino",
    "Ayrton",
    "Balbino",
    "Balduíno",
    "Baltasar",
    "Baltazar",
    "Barnabé",
    "Bartolomeu",
    "Basileu",
    "Basílio",
    "Batista",
    "Belarmino",
    "Belchior",
    "Belisário",
    "Belmiro",
    "Bendito",
    "Benedito",
    "Benito",
    "Benjamin",
    "Beto",
    "Bill",
    "Boanerges",
    "Bob",
    "Bonifácio",
    "Bóris",
    "Bosco",
    "Brandon",
    "Bruce",
    "Bryan",
    "Byron",
    "Cacildo",
    "Cadú",
    "Cael",
    "Caíco",
    "Caíque",
    "Calazan",
    "Calisto",
    "Calixto",
    "Calvin",
    "Camilo",
    "Cândido",
    "Canuto",
    "Casimiro",
    "Cassiano",
    "Cássio",
    "Castiel",
    "Cauã",
    "Cauê",
    "Celestino",
    "Celso",
    "César",
    "Charles",
    "Christian",
    "Christian",
    "Christopher",
    "Cirilo",
    "Ciro",
    "Cláudio",
    "Claus",
    "Clayton",
    "Clementino",
    "Clodomiro",
    "Clovis",
    "Clóvis",
    "Conrad",
    "Constantin",
    "Constantino",
    "Cosme",
    "Cristiano",
    "Cristóvão",
    "Cursino",
    "Custódio",
    "Dácio",
    "Dagoberto",
    "Dalmo",
    "Dalton",
    "Danilo",
    "Dante",
    "Dárcio",
    "Darius",
    "Deivid",
    "Delfino",
    "Delmar",
    "Demétrio",
    "Denis",
    "Denzel",
    "Derik",
    "Didier",
    "Dimas",
    "Dinis",
    "Diniz",
    "Dino",
    "Diógenes",
    "Dionísio",
    "Djalma",
    "Dom",
    "Domênico",
    "Dominic",
    "Donatello",
    "Donatílio",
    "Donato",
    "Donizete",
    "Douglas",
    "Douglas",
    "Durval",
    "Dylan",
    "Ed",
    "Éder",
    "Ederson",
    "Edivaldo",
    "Edmilson",
    "Edmir",
    "Edson",
    "Eliezer",
    "Élio",
    "Eliseo",
    "Eliseu",
    "Elísio",
    "Élton",
    "Emanuel",
    "Emaús",
    "Emerson",
    "Emílio",
    "Ênio",
    "Enrico",
    "Enrique",
    "Erasmo",
    "Erasmus",
    "Eriberto",
    "Erik",
    "Ernesto",
    "Esdras",
    "Eugénio",
    "Eurico",
    "Evaldo",
    "Evandro",
    "Evelásio",
    "Expedito",
    "Ezekiel",
    "Fabiano",
    "Faustino",
    "Fausto",
    "Felipe",
    "Felisberto",
    "Felismino",
    "Félix",
    "Ferdinand",
    "Ferdinando",
    "Fernando",
    "Fernão",
    "Firmino",
    "Flávio",
    "Florêncio",
    "Florentino",
    "Floriano",
    "Fortunato",
    "Francesco",
    "Francis",
    "Franco",
    "Frank",
    "Franklin",
    "Gael",
    "Galdino",
    "Galeno",
    "Galileu",
    "Gastão",
    "Gaudêncio",
    "Genaro",
    "Genésio",
    "Geovani",
    "Geraldo",
    "Germano",
    "Gerson",
    "Giancarlos",
    "Giani",
    "Gianluca",
    "Gilberto",
    "Gilmar",
    "Gilmar",
    "Gilson",
    "Giuseppe",
    "Glauco",
    "Golias",
    "Graciano",
    "Gregório",
    "Gualter",
    "Guarani",
    "Gumersindo",
    "Guy",
    "Haroldo",
    "Hélder",
    "Hélio",
    "Henry",
    "Herbert",
    "Hermano",
    "Hernâni",
    "Horácio",
    "Humberto",
    "Ike",
    "Irineu",
    "Isaías",
    "Isidoro",
    "Israel",
    "Ítalo",
    "Itamar",
    "Ivaldo",
    "Ivandro",
    "Ivanildo",
    "Jacinto",
    "Jack",
    "Jackson",
    "Jader",
    "Jadiel",
    "Jadir",
    "Jair",
    "Jairo",
    "Jamal",
    "Jamil",
    "Jandir",
    "Janilson",
    "Januário",
    "Jarbas",
    "Jason",
    "Jason",
    "Javier",
    "Jean",
    "Jefferson",
    "Jeremias",
    "Jessé",
    "Jessie",
    "Jessiel",
    "Jesualdo",
    "Jesus",
    "Joab",
    "Joelson",
    "Jofre",
    "Johnny",
    "Johnson",
    "Jonas",
    "Jonatã",
    "Josélio",
    "Joshua",
    "Josias",
    "Josué",
    "Juan",
    "Juliano",
    "Julião",
    "Júlio",
    "Júnior",
    "Jurandir",
    "Juvenal",
    "Kaique",
    "Kauã",
    "Kauan",
    "Kawan",
    "Kelvin",
    "Kennedy",
    "Klaus",
    "Kleber",
    "Lael",
    "Laerte",
    "Laertes",
    "Lauro",
    "Leon",
    "Leôncio",
    "Leonel",
    "Leónidas",
    "Leopoldo",
    "Lineu",
    "Lionel",
    "Lisandro",
    "Lívio",
    "Logan",
    "Luã",
    "Luan",
    "Luca",
    "Luciano",
    "Lúcio",
    "Luigi",
    "Luiz",
    "Lukas",
    "Luzio",
    "Macário",
    "Magnus",
    "Malvino",
    "Manassés",
    "Manoel",
    "Maomé",
    "Márcio",
    "Marcos",
    "Marcus",
    "Marley",
    "Marlon",
    "Martin",
    "Martinho",
    "Marvin",
    "Matheo",
    "Matheus",
    "Mathias",
    "Mathieu",
    "Maurílio",
    "Max",
    "Maximiliano",
    "Maxwell",
    "Mélvin",
    "Messias",
    "Micael",
    "Michael",
    "Michel",
    "Milo",
    "Milton",
    "Mizael",
    "Moacir",
    "Mohamed",
    "Nataniel",
    "Nazário",
    "Neil",
    "Nereu",
    "Nestor",
    "Newton",
    "Ney",
    "Nicola",
    "Nicolas",
    "Nildemar",
    "Nilo",
    "Nilson",
    "Nilton",
    "Nivaldo",
    "Nonato",
    "Norberto",
    "Norildo",
    "Norimar",
    "Odemar",
    "Odilson",
    "Odin",
    "Odorico",
    "Olin",
    "Omar",
    "Omer",
    "Onofre",
    "Orestes",
    "Orlandino",
    "Orlando",
    "Osias",
    "Osman",
    "Osmar",
    "Osório",
    "Osvaldo",
    "Otacílio",
    "Otávio",
    "Otto",
    "Ozael",
    "Pablo",
    "Paco",
    "Paolo",
    "Pascoal",
    "Patrício",
    "Patrick",
    "Paulino",
    "Pepe",
    "Percival",
    "Péricles",
    "Pierre",
    "Porfírio",
    "Querubim",
    "Quintino",
    "Radamés",
    "Rafaelo",
    "Raí",
    "Raimundo",
    "Ralf",
    "Ralph",
    "Ramiro",
    "Ramon",
    "Ramón",
    "Raoni",
    "Raphael",
    "Reginaldo",
    "Régis",
    "Reimão",
    "Reinaldo",
    "Renan",
    "Renato",
    "Renê",
    "Rivaldo",
    "Roberto",
    "Robson",
    "Rodney",
    "Rodolfo",
    "Roger",
    "Rogério",
    "Roland",
    "Rolando",
    "Romão",
    "Romário",
    "Romeo",
    "Rômulo",
    "Ronald",
    "Ronaldo",
    "Roni",
    "Rosendo",
    "Rúbens",
    "Rudesindo",
    "Rudolfo",
    "Ruy",
    "Ryan",
    "Sansão",
    "Saúl",
    "Saulo",
    "Sávio",
    "Selton",
    "Sertório",
    "Severino",
    "Sidney",
    "Silas",
    "Sílvio",
    "Simplício",
    "Sinésio",
    "Stefan",
    "Stefano",
    "Stenio",
    "Steve",
    "Steven",
    "Sydney",
    "Taciano",
    "Tadeu",
    "Tales",
    "Tamires",
    "Tâmiris",
    "Tarcísio",
    "Tarik",
    "Tarsício",
    "Telmo",
    "Tenório",
    "Teo",
    "Teobaldo",
    "Teodemiro",
    "Thales",
    "Theo",
    "Thiago",
    "Thomas",
    "Thomaz",
    "Tibúrcio",
    "Ticiano",
    "Tierry",
    "Timóteo",
    "Tito",
    "Tom",
    "Tomaz",
    "Tristão",
    "Troy",
    "Túlio",
    "Ubirajara",
    "Ubiratã",
    "Urbano",
    "Uriel",
    "Valdemar",
    "Valentino",
    "Vanderlei",
    "Vasco",
    "Venâncio",
    "Veríssimo",
    "Vicenzo",
    "Victor",
    "Vílmar",
    "Vilson",
    "Vinícius",
    "Virgílio",
    "Vital",
    "Vítor",
    "Vladimir",
    "Wagner",
    "Waldir",
    "Waldo",
    "Wallace",
    "Walter",
    "Washington",
    "Watson",
    "Webster",
    "Weller",
    "Wellington",
    "Wendel",
    "Wesley",
    "Will",
    "William",
    "Wilson",
]
SOBRENOMES = ['ALMEIDA', 'ALVES', 'ANDRADE', 'BARBOSA', 'BARROS', 'BATISTA', 'BORGES', 'CAMPOS', 'CARDOSO', 'CARVALHO', 'CASTRO',
    'COSTA', 'DIAS', 'DUARTE', 'FREITAS', 'FERNANDES', 'FERREIRA', 'GARCIA', 'GOMES', 'GONÇALVES', 'LIMA', 'LOPES', 'MACHADO', 'MARQUES', 'MARTINS', 'MEDEIROS',
    'MELO', 'MENDES', 'MIRANDA', 'MONTEIRO', 'MORAES', 'MOREIRA', 'MOURA', 'NASCIMENTO', 'NUNES', 'OLIVEIRA', 'PEREIRA', 'RAMOS', 'REIS', 'RIBEIRO', 'ROCHA',
    'SANTANA', 'SANTOS', 'SILVA', 'SOARES', 'SOUZA', 'TEIXEIRA', 'VIEIRA']
TIPOS_SANGUINEOS = ['O+', 'A+', 'B+', 'AB+', 'O−', 'A−', 'B−', 'AB−']
pnome = str(NOMES[ransom])
snome = str(SOBRENOMES[ransom1])
tsangue = str(TIPOS_SANGUINEOS[ransom2])
if month == 1 and day <= 20 or month == 12 and day >= 22:
        signo='Capricórnio'
elif month == 2 and day <= 19 or month == 1 and day >= 22:
        signo='Aquários'
elif month == 3 and day <= 21 or month == 2 and day >= 24:
        signo = 'Peixes'
elif month == 4 and day <= 20 or month == 3 and day >= 23:
        signo = 'Aries'
elif month == 5 and day <= 21 or month == 4 and day >= 23: 
        signo = 'Touro'
elif month == 6 and day <= 22 or month == 5 and day >= 23:
        signo = 'Gêmeos'
elif month == 7 and day <= 23 or month == 6 and day >= 22:
        signo = 'Cancer'
elif month == 8 and day <= 23 or month == 7 and day >= 21:
        signo = 'Leao'
elif month == 9 and day <= 23 or month == 8 and day >= 20:
        signo = 'Virgo'
elif month == 10 and day <= 24 or month == 9 and day >= 21:
        signo = 'Libra'
elif month == 11 and day <= 22 or month == 10 and day >= 19:
        signo = 'Escorpião'
elif month == 12 and day <= 22 or month == 11 and day >= 20:
        signo = 'Sagitário'
        
placa_gen = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","0","1","2","3","4","5","6","7","8","9"]
ransom1 = randint(0,35)
placa0 = placa_gen[ransom3]
ransom3 = randint(0,25)
placa1 = placa_gen[ransom3]
ransom3 = randint(0,25)
placa2 = placa_gen[ransom3]
placa3 = placa_gen[ransom1]
ransom1 = randint(0,35)
placa4 = placa_gen[ransom1]
ransom1 = randint(0,35)
placa5 = placa_gen[ransom1]
ransom1 = randint(0,35)
placa6 = placa_gen[ransom1]
ESTADOS = [
    'Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Distrito Federal','Espírito Santo','Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo','Sergipe','Tocantins',
]
ransom = randint(0,26)
if ransom == 0:
    shortname = "AC"
elif ransom == 1:
    shortname = "AL"
elif ransom == 2:
    shortname = "AP"
elif ransom == 3:
    shortname = "AM"
elif ransom == 4:
    shortname = "BA"
elif ransom == 5:
    shortname = "CE"
elif ransom == 6:
    shortname = "DF"
elif ransom == 7:
    shortname = "ES"
elif ransom == 8:
    shortname = "GO"
elif ransom == 9:
    shortname = "MA"
elif ransom == 10:
    shortname = "MT"
elif ransom == 11:
    shortname = "MS"
elif ransom == 12:
    shortname = "MG"
elif ransom == 13:
    shortname = "PA"
elif ransom == 14:
    shortname = "PB"
elif ransom == 15:
    shortname = "PR"
elif ransom == 16:
    shortname = "PE"
elif ransom == 17:
    shortname = "PI"
elif ransom == 18:
    shortname = "RJ"
elif ransom == 19:
    shortname = "RN"
elif ransom == 20:
    shortname = "RS"
elif ransom == 21:
    shortname = "RO"
elif ransom == 22:
    shortname = "RR"
elif ransom == 23:
    shortname = "SC"
elif ransom == 24:
    shortname = "SP"
elif ransom == 25:
    shortname = "SE"
elif ransom == 26:
    shortname = "TO"
else:
    shortname = "error"
print(shortname)
estado=ESTADOS[ransom]
print(age)
print(pnome)
print(snome)
print(tsangue)
nascimento=('{}/{}/{}'.format(day,month,year))
print(signo)
placa=('{}{}{}-{}{}{}{}'.format(placa0,placa1,placa2,placa3,placa4,placa5,placa6))
#return shortname,estado,age,pnome,snome,tsangue,nascimento,signo,placa
